### ISSUE TITLE
Create a logo font `BJ`

### ISSUE THREAD

**Issue by paragasu** [phisoft/batangaujaya-web#1]
Create a logo for Batangau Jaya Sdn Bhd
Client request specifically for the letter `BJ` as a logo font. 

Find font face suitable to show batangau core business - Trading & construction service

**Comment by Clairefrancis95** [comment]
![batangau jaya logo](https://user-images.githubusercontent.com/48192938/54658533-cd6ff980-4b08-11e9-8585-05f44ddd1860.jpg)

**Comment by paragasu** [comment]
@Clairefrancis95 client prefer logo like this. So, we just modify this logo for batangau jaya.

![logo-bj-1-728](https://user-images.githubusercontent.com/27353/54908607-42856980-4f23-11e9-81a8-5f4e83274ce4.jpg)

**Comment by Clairefrancis95** [comment]
![BJlogo](https://user-images.githubusercontent.com/48192938/54967523-90957e00-4fb2-11e9-8b28-7182ca7a29fa.jpg)

**Comment by Clairefrancis95** [comment]
![BJlogo1](https://user-images.githubusercontent.com/48192938/54977475-68207a80-4fd8-11e9-9602-913932a14a2f.png)

**Comment by Clairefrancis95** [comment]
![BJlogo2](https://user-images.githubusercontent.com/48192938/54977744-365be380-4fd9-11e9-8e33-4eb97d2f804b.png)
